#pragma once
#include <iostream>
enum RpcError : std::uint16_t
{
	SUCCESS = 0,
	GENERIC_NET_ERROR = 1,
	DATABASE_ERROR = 2,
	PLAYER_STATE_ERROR = 3,
	UNKNOWN_RPC_ERROR = 4,
	USER_ALREADY_LOGGED_IN = 100,
	USER_ALREADY_LOGGED_IN_ELSEWHERE = 101,
	NOT_LOGGED_IN = 102,
	WRONG_PASSWORD = 103,
	REGISTER_FAILED = 104,
	ALREADY_IN_SELECTED_ROOM = 200,
	ROOM_NOT_EXIST = 201,
	ROOM_ALREADY_EXIST = 202,
	ROOM_ID_OVERFLOW = 203,
	ROOM_TYPE_ERROR = 204,
};