#pragma once
#include <iostream>
enum RpcError : std::uint16_t
{
	SUCCESS = 0,
	GENERIC_NET_ERROR = 1,
	DATABASE_ERROR = 2,
	PLAYER_STATE_ERROR = 3,
	UNKNOWN_RPC_ERROR = 4,
	USER_ALREADY_LOGGED_IN = 100,
	USER_ALREADY_LOGGED_IN_ELSEWHERE = 101,
	NOT_LOGGED_IN = 102,
	WRONG_PASSWORD = 103,
	REGISTER_FAILED = 104,
	SQL_COMMAND_FAILED = 105,
	ALREADY_IN_SELECTED_ROOM = 200,
	ROOM_NOT_EXIST = 201,
	ROOM_ALREADY_EXIST = 202,
	ROOM_ID_OVERFLOW = 203,
	ROOM_TYPE_ERROR = 204,
	// Poker room errors
	POKER_INSUFFICIENT_CHIPS = 300,
	POKER_BUYIN_FAILED = 301,
	POKER_BLINDS_NOT_SET = 302,
	POKER_PLAYER_NOT_SEATED = 303,
	POKER_ALREADY_IN_HAND = 304,
};